In [2]:
import pandas as pd
from seaborn.external.docscrape import header
!pip install kagglehub opencv-python seaborn matplotlib scikit-learn

Collecting kagglehub
  Downloading kagglehub-0.4.2-py3-none-any.whl.metadata (38 kB)
Collecting opencv-python
  Using cached opencv_python-4.13.0.90-cp37-abi3-manylinux_2_28_x86_64.whl.metadata (19 kB)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting matplotlib
  Using cached matplotlib-3.10.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (52 kB)
Collecting scikit-learn
  Using cached scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Collecting kagglesdk<1.0,>=0.1.14 (from kagglehub)
  Using cached kagglesdk-0.1.15-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in ./.venv/lib/python3.12/site-packages (from kagglehub) (26.0)
Requirement already satisfied: pyyaml in ./.venv/lib/python3.12/site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in ./.venv/lib/python3.12/site-packages (from kagglehub) (2.32.5)
Collecting tqdm (from kagglehub)
  Using cached tqdm-4.67.2-py3-none-any.whl.metadata (57 kB)
Collecting numpy>=2 (from opencv-python)
  Using cached numpy-2.4.2-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting pandas>=1.2 (from seaborn)
  Using cached pandas-3.0.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Using cached fonttools-4.61.1-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl.metadata (114 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Using cached kiwisolver-1.4.9-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (6.3 kB)
Collecting pillow>=8 (from matplotlib)
  Using cached pillow-12.1.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.8 kB)
Collecting pyparsing>=3 (from matplotlib)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in ./.venv/lib/python3.12/site-packages (from matplotlib) (2.9.0.post0)
Collecting scipy>=1.10.0 (from scikit-learn)
  Using cached scipy-1.17.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting protobuf (from kagglesdk<1.0,>=0.1.14->kagglehub)
  Downloading protobuf-6.33.5-cp39-abi3-manylinux2014_x86_64.whl.metadata (593 bytes)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.12/site-packages (from requests->kagglehub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.12/site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.venv/lib/python3.12/site-packages (from requests->kagglehub) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in ./.venv/lib/python3.12/site-packages (from requests->kagglehub) (2026.1.4)
Downloading kagglehub-0.4.2-py3-none-any.whl (69 kB)
Using cached opencv_python-4.13.0.90-cp37-abi3-manylinux_2_28_x86_64.whl (72.9 MB)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached matplotlib-3.10.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.7 MB)
Using cached scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (8.9 MB)
Using cached contourpy-1.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (362 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.61.1-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl (5.0 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached kagglesdk-0.1.15-py3-none-any.whl (160 kB)
Using cached kiwisolver-1.4.9-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.5 MB)
Using cached numpy-2.4.2-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
Using cached pandas-3.0.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
Using cached pillow-12.1.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (7.0 MB)
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
Using cached scipy-1.17.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (35.0 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Using cached tqdm-4.67.2-py3-none-any.whl (78 kB)
Downloading protobuf-6.33.5-cp39-abi3-manylinux2014_x86_64.whl (323 kB)
Installing collected packages: tqdm, threadpoolctl, pyparsing, protobuf, pillow, numpy, kiwisolver, joblib, fonttools, cycler, scipy, pandas, opencv-python, kagglesdk, contourpy, scikit-learn, matplotlib, kagglehub, seaborn
Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.61.1 joblib-1.5.3 kagglehub-0.4.2 kagglesdk-0.1.15 kiwisolver-1.4.9 matplotlib-3.10.8 numpy-2.4.2 opencv-python-4.13.0.90 pandas-3.0.0 pillow-12.1.0 protobuf-6.33.5 pyparsing-3.3.2 scikit-learn-1.8.0 scipy-1.17.0 seaborn-0.13.2 threadpoolctl-3.6.0 tqdm-4.67.2

[notice] A new release of pip is available: 24.3.1 -> 26.0
[notice] To update, run: pip install --upgrade pip

In [3]:
import kagglehub
import os

# Define the target directory
download_dir = './dataset'
os.makedirs(download_dir, exist_ok=True)

download_path = kagglehub.dataset_download(
    'mdraselsarker/mot15-challenge-dataset',
)

print(f"Dataset downloaded to: {download_path}")

/home/yogendra/workspace/python/university/Object-detection-and-tracking/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading to /home/yogendra/.cache/kagglehub/datasets/mdraselsarker/mot15-challenge-dataset/1.archive...

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.22G/1.22G [05:45<00:00, 3.79MB/s]

Extracting files...

Dataset downloaded to: /home/yogendra/.cache/kagglehub/datasets/mdraselsarker/mot15-challenge-dataset/versions/1

In [58]:
import os
import pandas as pd

base_dir = './dataset/'

object_detection_columns = [
    "frame_id",
    "object_id",
    "x_coordinate",
    "y_coordinate",
    "width",
    "height",
    "confidence",
    "x_init",
    "y_init",
    "z_init"
]

In [59]:
import configparser

config = configparser.ConfigParser()

def get_features_df(folder_path: str):
    folders = sorted(os.listdir(folder_path))
    features = []

    for folder_id, folder in enumerate(folders):
        print(f"File - {folder}")

        config_file_path = folder_path + folder + "/seqinfo.ini"
        config.read(config_file_path)

        metadata = dict(config.items('Sequence'))
        for key in ["name", "imdir", "framerate", "seqlength", "imwidth", "imheight", "imext"]:
            if key not in metadata:
                raise Exception(f"Key {key} not found in seqinfo.ini in folder {folder}")

        top_level_feat = {
                "video_id": folder_id,
                "video_name": metadata["name"],
                "image_width": metadata["imwidth"],
                "image_height": metadata["imheight"],
            }

        image_dir_path = folder_path + folder + "/" + metadata["imdir"]
        image_files = sorted(os.listdir(image_dir_path))
        for frame_id, image_file in enumerate(image_files):
            features.append({
                **top_level_feat,
                "frame_id": frame_id,
                "image_path": image_dir_path + "/" + image_file
            })
    return pd.DataFrame(columns=['video_id', 'video_name', 'image_width', 'image_height', 'frame_id', 'image_path'], data=features)

def get_detection_df(folder_path: str):
    folders = sorted(os.listdir(folder_path))
    object_detection_df = pd.DataFrame(columns=object_detection_columns)

    for folder_id, folder in enumerate(folders):
        detection_file_path = folder_path + folder + "/det/det.txt"
        det_df = pd.read_csv(detection_file_path, header=None, names = object_detection_columns)
        det_df["video_id"] = folder_id
        object_detection_df = pd.concat([object_detection_df, det_df], axis=0)

    object_detection_df['video_id'] = object_detection_df['video_id'].astype(int)
    object_detection_df['frame_id'] = object_detection_df['frame_id'].map(lambda x: x - 1)
    return object_detection_df

def get_ground_truth_df(folder_path: str):
    folders = sorted(os.listdir(folder_path))
    ground_truth_detection_df = pd.DataFrame(columns=object_detection_columns)

    for folder_id, folder in enumerate(folders):
        gt_file_path = folder_path + folder + "/gt/gt.txt"
        gt_df = pd.read_csv(gt_file_path, header=None, names = object_detection_columns)
        gt_df["video_id"] = folder_id
        ground_truth_detection_df = pd.concat([ground_truth_detection_df, gt_df], axis=0)

    ground_truth_detection_df['video_id'] = ground_truth_detection_df['video_id'].astype(int)
    ground_truth_detection_df['frame_id'] = ground_truth_detection_df['frame_id'].map(lambda x: x - 1)
    return ground_truth_detection_df

In [60]:
train_df = get_features_df(base_dir + 'train/')
det_df = get_detection_df(base_dir + 'train/')
gt_df = get_ground_truth_df(base_dir + 'train/')
train_df.to_csv('./dataset/train.csv')
det_df.to_csv('./dataset/train_det.csv')
gt_df.to_csv('./dataset/train_gt.csv')

File - ADL-Rundle-6
File - ADL-Rundle-8
File - ETH-Bahnhof
File - ETH-Pedcross2
File - ETH-Sunnyday
File - KITTI-13
File - KITTI-17
File - PETS09-S2L1
File - TUD-Campus
File - TUD-Stadtmitte
File - Venice-2

In [61]:
train_df.head()

,video_id,video_name,image_width,image_height,frame_id,image_path
0,0,ADL-Rundle-6,1920,1080,0,./dataset/train/ADL-Rundle-6/img1/000001.jpg
1,0,ADL-Rundle-6,1920,1080,1,./dataset/train/ADL-Rundle-6/img1/000002.jpg
2,0,ADL-Rundle-6,1920,1080,2,./dataset/train/ADL-Rundle-6/img1/000003.jpg
3,0,ADL-Rundle-6,1920,1080,3,./dataset/train/ADL-Rundle-6/img1/000004.jpg
4,0,ADL-Rundle-6,1920,1080,4,./dataset/train/ADL-Rundle-6/img1/000005.jpg

In [62]:
det_df.head()

,frame_id,object_id,x_coordinate,y_coordinate,width,height,confidence,x_init,y_init,z_init,video_id
0,0,-1,1689,385,146.62,332.71,67.567,-1,-1,-1,0
1,0,-1,1303,503,61.514,139.59,29.439,-1,-1,-1,0
2,0,-1,1258,569,40.123,91.049,19.601,-1,-1,-1,0
3,0,-1,31,525,113.37,257.27,17.013,-1,-1,-1,0
4,0,-1,1800,483,94.66,214.81,11.949,-1,-1,-1,0

In [63]:
gt_df.head()

,frame_id,object_id,x_coordinate,y_coordinate,width,height,confidence,x_init,y_init,z_init,video_id
0,0,1,1703,385,157,339,1,-1,-1,-1,0
1,0,3,1293,455,83,213,1,-1,-1,-1,0
2,0,4,259,449,101,261,1,-1,-1,-1,0
3,0,5,1253,529,55,127,1,-1,-1,-1,0
4,1,1,1699,383,159,341,1,-1,-1,-1,0

In [64]:
test_df = get_features_df(base_dir + 'test/')
test_det_df = get_detection_df(base_dir + 'test/')
test_df.to_csv('./dataset/test.csv')
test_det_df.to_csv('./dataset/test_det.csv')

File - ADL-Rundle-1
File - ADL-Rundle-3
File - AVG-TownCentre
File - ETH-Crossing
File - ETH-Jelmoli
File - ETH-Linthescher
File - KITTI-16
File - KITTI-19
File - PETS09-S2L2
File - TUD-Crossing
File - Venice-1

In [65]:
test_df.head()

,video_id,video_name,image_width,image_height,frame_id,image_path
0,0,ADL-Rundle-1,1920,1080,0,./dataset/test/ADL-Rundle-1/img1/000001.jpg
1,0,ADL-Rundle-1,1920,1080,1,./dataset/test/ADL-Rundle-1/img1/000002.jpg
2,0,ADL-Rundle-1,1920,1080,2,./dataset/test/ADL-Rundle-1/img1/000003.jpg
3,0,ADL-Rundle-1,1920,1080,3,./dataset/test/ADL-Rundle-1/img1/000004.jpg
4,0,ADL-Rundle-1,1920,1080,4,./dataset/test/ADL-Rundle-1/img1/000005.jpg

In [66]:
test_det_df.head()

,frame_id,object_id,x_coordinate,y_coordinate,width,height,confidence,x_init,y_init,z_init,video_id
0,0,-1,1344,386,30.903,70.127,85.914,-1,-1,-1,0
1,0,-1,771,357,26.0,59.0,51.759,-1,-1,-1,0
2,0,-1,1087,345,28.302,64.224,45.699,-1,-1,-1,0
3,0,-1,817,340,36.723,83.333,41.611,-1,-1,-1,0
4,0,-1,869,313,67.474,153.11,36.659,-1,-1,-1,0